apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: standard  # Changed to standard for Minikube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi